packages:
  - apps/*
  - libs/*
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma
  - zenstack
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
